import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import type { NextPage } from 'next'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

function MyApp({ Component, pageProps }: AppProps) {
  return <>  
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        crossOrigin="anonymous"
      /> 
      <script src="https://cdn.tailwindcss.com"></script>
    </Head> 
    <Component {...pageProps} />
  </>

  
}

export default MyApp
